
 name: app_build
 on: [pull_request, push]
 jobs:
   build:
     runs-on: ubuntu-latest
     steps:
     - uses: actions/checkout@v2
     - uses: actions/setup-java@v1
       with:
         java-version: '12.x'
     - uses: subosito/flutter-action@v1
       with:
         flutter-version: '1.22.4'
     - run: App/flutter pub get
     - run: App/flutter test
     - run: App/flutter build apk